"""Pinned Swei Gothic regional fonts, subset to reviewed UI CJK characters."""
import concurrent.futures
import hashlib
import json
from pathlib import Path
import urllib.request
from fontTools import subset
from fontTools.ttLib import TTFont

REV='c363a1d845aa782a71b7a068b5db0aff3f83ee86'
BASE=f'https://raw.githubusercontent.com/max32002/swei-gothic/{REV}/'
CACHE=Path('.local/font-source');CACHE.mkdir(parents=True,exist_ok=True)
OUT=Path('assets/fonts/swei');OUT.mkdir(parents=True,exist_ok=True)
css=['/* Generated by tools/build-fonts.py; keep fonts local, with their OFL license. */']
manifest={'repository':'https://github.com/max32002/swei-gothic','revision':REV,'files':[]}
def download(item):
 region,weight=item;name=f'SweiGothicCJK{region.lower()}-{weight}.woff2';target=CACHE/name
 if not target.exists():
  data=urllib.request.urlopen(BASE+f'WebFont/CJK%20{region}/'+name,timeout=90).read();target.write_bytes(data)
 return item,target
items=[(r,w) for r in ['SC','TC','JP'] for w in ['Medium','Bold','Black']]
sources=dict(concurrent.futures.ThreadPoolExecutor(max_workers=3).map(download,items))
for region,locale in [('SC','zh-Hans'),('TC','zh-Hant'),('JP','ja')]:
 messages=json.loads((Path('src/i18n/locales')/(locale+'.json')).read_text(encoding='utf8'))
 chars=set(''.join(messages.values())+'简体中文繁體中文日本語言語语言')
 codes={ord(c) for c in chars if 0x3000<=ord(c)<=0x9fff or 0xf900<=ord(c)<=0xffef}
 for weight,range_ in [('Medium','400 600'),('Bold','700 900'),('Black','400 900')]:
  source=sources[(region,weight)];name=f'{region}-{weight}.woff2'
  existing=TTFont(OUT/name) if (OUT/name).exists() else None
  if existing is None or codes-set(existing.getBestCmap()):
   font=TTFont(source)
   missing=codes-set(font.getBestCmap())
   if missing: raise ValueError(f'{region} missing glyphs: '+''.join(chr(c) for c in sorted(missing)))
   options=subset.Options();options.flavor='woff2';options.recalc_timestamp=False
   worker=subset.Subsetter(options=options);worker.populate(unicodes=codes);worker.subset(font)
   font.save(OUT/name)
   print('Updated '+name,flush=True)
  family=f'Swei {region}'+(' Display' if weight=='Black' else '')
  css.append(f"@font-face {{ font-family:'{family}'; src:url('../assets/fonts/swei/{name}') format('woff2'); font-style:normal; font-weight:{range_}; font-display:swap; unicode-range:U+3000-9FFF,U+F900-FFEF; }}")
  manifest['files'].append({'path':name,'source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'sha256':hashlib.sha256((OUT/name).read_bytes()).hexdigest(),'bytes':(OUT/name).stat().st_size,'characters':len(codes)})
(OUT/'OFL.txt').write_bytes(urllib.request.urlopen(BASE+'SIL_Open_Font_License_1.1.txt',timeout=30).read())
(OUT/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
Path('styles/cjk-fonts.css').write_text('\n'.join(css)+'\n')
print(json.dumps({'fonts':len(items),'total_bytes':sum(f['bytes'] for f in manifest['files'])}))
